version: '3.3'
services:
  bds_web:
    build:
      context: .
      args:
        - ALGOLIA_APPID=pl0K4C57LHC4
        - ALGOLIA_APPKEY=74d8852573f9c6ff69b6e9e87f05efb6
        - BACKEND_HOST=https://muadunggia.com.vn/real-estate-api/api/v2
        - ADMINISTRATIVE=https://muadunggia.com.vn/administrative-geojson
        - TILE_API=https://muadunggia.com.vn/map-api/rest/map
        - GEOCODING_API=https://muadunggia.com.vn/geocoding
        - AUTH_API=http://164.68.125.241:4081/
        - BACKEND_HOST_LOCAL=http://164.68.125.241:4081/
        - BACKEND_LOCAL=http://164.68.125.241:4081/
        - GOOGLE_MAP_API_KEY=AIzaSyBJ3wiDATfk8Sb1i5OfhKzJOjNdJTEG0ac

    ports:
      - '5000:80'
    command: [nginx-debug, '-g', 'daemon off;']
