import React from 'react';
import ContentLoader from 'react-content-loader';
import { Row, Col } from 'antd';
import styles from './index.less';

const MyLoader = (props) => (
  <>
    <Row gutter={[32, 32]}>
      <Col className={styles.customEstateComponent} md={12} lg={12} xxl={12}>
        <ContentLoader
          speed={2}
          width={400}
          height={240}
          className={styles.customSkeletonWidth}
          viewBox="0 0 400 240"
          backgroundColor="#bababa"
          foregroundColor="#ecebeb"
          {...props}
        >
          <rect
            x="0"
            y="179"
            className={styles.customSkeletonWidth}
            rx="3"
            ry="3"
            width="352"
            height="6"
          />
          <rect
            x="0"
            y="219"
            className={styles.customSkeletonWidth}
            rx="3"
            ry="3"
            width="178"
            height="6"
          />
          <rect
            x="302"
            y="49"
            className={styles.customSkeletonWidth}
            rx="0"
            ry="0"
            width="0"
            height="3"
          />
          <rect
            x="0"
            y="0"
            className={styles.customSkeletonWidth}
            rx="0"
            ry="0"
            width="352"
            height="164"
          />
          <rect
            x="0"
            y="198"
            className={styles.customSkeletonWidth}
            rx="3"
            ry="3"
            width="280"
            height="6"
          />
        </ContentLoader>
      </Col>
      <Col className={styles.customEstateComponent} md={12} lg={12} xxl={12}>
        <ContentLoader
          speed={2}
          width={400}
          height={240}
          className={styles.customSkeletonWidth}
          viewBox="0 0 400 240"
          backgroundColor="#bababa"
          foregroundColor="#ecebeb"
          {...props}
        >
          <rect
            x="0"
            y="179"
            className={styles.customSkeletonWidth}
            rx="3"
            ry="3"
            width="352"
            height="6"
          />
          <rect
            x="0"
            y="219"
            className={styles.customSkeletonWidth}
            rx="3"
            ry="3"
            width="178"
            height="6"
          />
          <rect
            x="302"
            y="49"
            className={styles.customSkeletonWidth}
            rx="0"
            ry="0"
            width="0"
            height="3"
          />
          <rect
            x="0"
            y="0"
            className={styles.customSkeletonWidth}
            rx="0"
            ry="0"
            width="352"
            height="164"
          />
          <rect
            x="0"
            y="198"
            className={styles.customSkeletonWidth}
            rx="3"
            ry="3"
            width="280"
            height="6"
          />
        </ContentLoader>
      </Col>
      <Col className={styles.customEstateComponent} md={12} lg={12} xxl={12}>
        <ContentLoader
          speed={2}
          width={400}
          height={240}
          className={styles.customSkeletonWidth}
          viewBox="0 0 400 240"
          backgroundColor="#bababa"
          foregroundColor="#ecebeb"
          {...props}
        >
          <rect
            x="0"
            y="179"
            className={styles.customSkeletonWidth}
            rx="3"
            ry="3"
            width="352"
            height="6"
          />
          <rect
            x="0"
            y="219"
            className={styles.customSkeletonWidth}
            rx="3"
            ry="3"
            width="178"
            height="6"
          />
          <rect
            x="302"
            y="49"
            className={styles.customSkeletonWidth}
            rx="0"
            ry="0"
            width="0"
            height="3"
          />
          <rect
            x="0"
            y="0"
            className={styles.customSkeletonWidth}
            rx="0"
            ry="0"
            width="352"
            height="164"
          />
          <rect
            x="0"
            y="198"
            className={styles.customSkeletonWidth}
            rx="3"
            ry="3"
            width="280"
            height="6"
          />
        </ContentLoader>
      </Col>
      <Col className={styles.customEstateComponent} md={12} lg={12} xxl={12}>
        <ContentLoader
          speed={2}
          width={400}
          height={240}
          className={styles.customSkeletonWidth}
          viewBox="0 0 400 240"
          backgroundColor="#bababa"
          foregroundColor="#ecebeb"
          {...props}
        >
          <rect
            x="0"
            y="179"
            className={styles.customSkeletonWidth}
            rx="3"
            ry="3"
            width="352"
            height="6"
          />
          <rect
            x="0"
            y="219"
            className={styles.customSkeletonWidth}
            rx="3"
            ry="3"
            width="178"
            height="6"
          />
          <rect
            x="302"
            y="49"
            className={styles.customSkeletonWidth}
            rx="0"
            ry="0"
            width="0"
            height="3"
          />
          <rect
            x="0"
            y="0"
            className={styles.customSkeletonWidth}
            rx="0"
            ry="0"
            width="352"
            height="164"
          />
          <rect
            x="0"
            y="198"
            className={styles.customSkeletonWidth}
            rx="3"
            ry="3"
            width="280"
            height="6"
          />
        </ContentLoader>
      </Col>
      <Col className={styles.customEstateComponent} md={12} lg={12} xxl={12}>
        <ContentLoader
          speed={2}
          width={400}
          height={240}
          className={styles.customSkeletonWidth}
          viewBox="0 0 400 240"
          backgroundColor="#bababa"
          foregroundColor="#ecebeb"
          {...props}
        >
          <rect
            x="0"
            y="179"
            className={styles.customSkeletonWidth}
            rx="3"
            ry="3"
            width="352"
            height="6"
          />
          <rect
            x="0"
            y="219"
            className={styles.customSkeletonWidth}
            rx="3"
            ry="3"
            width="178"
            height="6"
          />
          <rect
            x="302"
            y="49"
            className={styles.customSkeletonWidth}
            rx="0"
            ry="0"
            width="0"
            height="3"
          />
          <rect
            x="0"
            y="0"
            className={styles.customSkeletonWidth}
            rx="0"
            ry="0"
            width="352"
            height="164"
          />
          <rect
            x="0"
            y="198"
            className={styles.customSkeletonWidth}
            rx="3"
            ry="3"
            width="280"
            height="6"
          />
        </ContentLoader>
      </Col>
      <Col className={styles.customEstateComponent} md={12} lg={12} xxl={12}>
        <ContentLoader
          speed={2}
          width={400}
          height={240}
          className={styles.customSkeletonWidth}
          viewBox="0 0 400 240"
          backgroundColor="#bababa"
          foregroundColor="#ecebeb"
          {...props}
        >
          <rect
            x="0"
            y="179"
            className={styles.customSkeletonWidth}
            rx="3"
            ry="3"
            width="352"
            height="6"
          />
          <rect
            x="0"
            y="219"
            className={styles.customSkeletonWidth}
            rx="3"
            ry="3"
            width="178"
            height="6"
          />
          <rect
            x="302"
            y="49"
            className={styles.customSkeletonWidth}
            rx="0"
            ry="0"
            width="0"
            height="3"
          />
          <rect
            x="0"
            y="0"
            className={styles.customSkeletonWidth}
            rx="0"
            ry="0"
            width="352"
            height="164"
          />
          <rect
            x="0"
            y="198"
            className={styles.customSkeletonWidth}
            rx="3"
            ry="3"
            width="280"
            height="6"
          />
        </ContentLoader>
      </Col>
    </Row>
  </>
);

export default MyLoader;
